### ISSUE TITLE
Build hybrid ABI packages with man pages

### ISSUE THREAD

**Issue by kwitaszczyk** [CTSRD-CHERI/poudriere-infrastructure#18]
We should ship packages with man pages once https://github.com/CTSRD-CHERI/cheribsd/issues/1340 is ready.

**Comment by brooksdavis** [comment]
We definitely want to get here and should do this for hybrid pkgs. I'm less sure about cheriabi at the moment since that would mean turning on the `DOCS` option.

**Comment by kwitaszczyk** [comment]
> We definitely want to get here and should do this for hybrid pkgs. I'm less sure about cheriabi at the moment since that would mean turning on the `DOCS` option.

I agree. Let's investigate man pages for CheriABI packages separately.

**Comment by kwitaszczyk** [comment]
Hybrid ABI packages with man pages are available at pkg.CheriBSD.org now.
